POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTc1NDI1NTY3NywiZXhwIjoxNzU0MzQyMDc3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.J_oUx7bYqBkVou_ioz2JmfTK0WL7x_5q59z9fyizy5M

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTc1NDI1NTY3NywiZXhwIjoxNzU0MzQyMDc3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.J_oUx7bYqBkVou_ioz2JmfTK0WL7x_5q59z9fyizy5M"
}