POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzU0MjUyOTU0LCJleHAiOjE3NTQyNTY1NTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Nm9Wk9FiqkQC7oaVmvEDEFmSQ0Nk8WZBXPIU5HPOm84
{
  "name": "typescript",
  "slug": "typescript",
  "description": "All posts javascript"
}